META_ARC: "udatban_r50_l234"

BACKBONE:
    TYPE: "resnet50"
    KWARGS:
        used_layers: [2, 3, 4]
    PRETRAINED: ''
    TRAIN_LAYERS: ['layer2', 'layer3', 'layer4']
    TRAIN_EPOCH: 0
    LAYERS_LR: 0.1

ADJUST:
    ADJUST: True
    TYPE: "AdjustAllLayer"
    KWARGS:
        in_channels: [512, 1024, 2048]
        out_channels: [256, 256, 256]

ALIGN:
    ALIGN: true
    TYPE: "EFM"
    KWARGS:
        adj_channel: 256

BAN:
    BAN: True
    TYPE: 'MultiBAN'
    KWARGS:
        in_channels: [256, 256, 256]
        cls_out_channels: 2  # if use sigmoid cls, cls_out_channel = 1 else 2
        weighted: True

POINT:
    STRIDE: 8

TRACK:
    TYPE: 'SiamBANTracker'
    WINDOW_INFLUENCE: 0.385
    PENALTY_K: 0.02
    LR: 0.473
    EXEMPLAR_SIZE: 127
    INSTANCE_SIZE: 255
    BASE_SIZE: 8
    CONTEXT_AMOUNT: 0.5

TRAIN:
    EPOCH: 31
    START_EPOCH: 0
    BATCH_SIZE: 16
    BASE_LR: 0.0015
    BASE_LR_d: 0.005
    CLS_WEIGHT: 1.0
    LOC_WEIGHT: 1.0
    PRETRAINED: '/media/w/719A549756118C56/HGG/SAM-DA-main/checkpoint/siamban.pth'
    RESUME: ''

    LR:
        TYPE: 'log'
        KWARGS:
            start_lr: 0.0015
            end_lr: 0.000015
    LR_WARMUP:
        TYPE: 'step'
        EPOCH: 5
        KWARGS:
            start_lr: 0.0003
            end_lr: 0.0015
            step: 1

DATASET:
    NAMES:
    - 'VID'
    #- 'YOUTUBEBB'
    #- 'COCO'
    #- 'DET'
    - 'GOT10K'
    #- 'LASOT'

    VIDEOS_PER_EPOCH: 20000

    TEMPLATE:
        SHIFT: 4
        SCALE: 0.05
        BLUR: 0.0
        FLIP: 0.0
        COLOR: 1.0

    SEARCH:
        SHIFT: 64
        SCALE: 0.18
        BLUR: 0.2
        FLIP: 0.0
        COLOR: 1.0

    NEG: 0.2
    GRAY: 0.2
